# A/B Test Aggregated Metrics Analysis

## Install packages if not already installed
# install.packages("dplyr")
# install.packages("ggplot2")
# install.packages("reshape2")

library(dplyr)
library(ggplot2)
library(reshape2)


df <- read.csv("synthetic_experiment_data_group_yakovlev.csv")

## Customer Retention Rate (CRR)
#---> Measures the percentage of customers who continue to use DoorDash over time. 
#---> High CRR indicates that customers are satisfied with the service and keep coming back for more orders. 
#---> It's crucial for DoorDash to retain customers as it contributes to long-term revenue and business growth

crr <- n_distinct(df$customerID[df$customerID %in% df$customerID[df$customerID %in% df$customerID] > 1]) / n_distinct(df$customerID) * 100


## Average Order Value (AOV)
#---> Average amount spent by customers per order. Increasing AOV indicates higher 
#---> customer spending, which directly impacts revenue.

aov <- mean(tapply(df$satisfaction, df$customerID, sum, na.rm = TRUE) / tapply(df$customerID, df$customerID, length))


# Customer Churn Rate
#---> Percentage of customers who stop using DoorDash within a specific period. 
#---> High churn indicates dissatisfaction or loss of interest among customers. 
#---> DoorDash needs to minimize churn to maintain a loyal customer base.")

churn_rate <- n_distinct(df$customerID[df$customerID %in% df$customerID[df$customerID %in% df$customerID] == 1]) / n_distinct(df$customerID) * 100


# On-Time Delivery Rate
#---> Percentage of orders delivered within the expected delivery time. 
#---> High on-time delivery rate signifies efficiency and reliability, leading 
#---> to better customer satisfaction and retention. DoorDash should focus on 
#---> optimizing delivery operations to ensure timely order fulfillment.

on_time_delivery_rate <- sum(df$actualDeliveryTime <= df$expectedDeliveryTime) / nrow(df) * 100


# Customer Lifetime Value (CLV)
#---> Total revenue generated by each customer throughout their relationship with DoorDash. 
#---> Increasing CLV requires building strong customer relationships and maximizing customer value over time. 
#---> DoorDash can implement loyalty programs and personalized offerings to enhance CLV and drive long-term profitability.

#---> Existing rewards program (2023): https://www.restaurantbusinessonline.com/technology/doordash-adds-loyalty-programs-part-app-revamp
#-----> Restaurants set up their own loyalty program where customers have a better in-app experience; similar to Amazon app functionalities lol (essentially to mimick in-person shopping)


clv <- sum(tapply(df$satisfaction, df$customerID, sum, na.rm = TRUE))

# Metric table
metrics_all_customers <- data.frame(
  metric = c("Customer Retention Rate", "Average Order Value", "Customer Churn Rate", "On-Time Delivery Rate", "Customer Lifetime Value"),
  value = c(crr, aov, churn_rate, on_time_delivery_rate, clv),
  type = c("Success Metric", "Success Metric", "Guardrail Metric", "Guardrail Metric", "Tracking Metric")
)

metrics_all_customers